
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 24 10:49:11 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 20;
  public static final int IDENT = 28;
  public static final int PLUS = 5;
  public static final int RBRACE = 4;
  public static final int RPAREN = 6;
  public static final int EQUAL = 10;
  public static final int CHAR = 26;
  public static final int RETURN = 23;
  public static final int LPAREN = 18;
  public static final int LBRACE = 3;
  public static final int BOOLEAN = 27;
  public static final int INC = 21;
  public static final int SEMIC = 8;
  public static final int COMMA = 9;
  public static final int NUMBER = 25;
  public static final int PERC = 16;
  public static final int EOF = 0;
  public static final int DIV = 14;
  public static final int PROG = 2;
  public static final int DEC = 24;
  public static final int MINUS = 15;
  public static final int PRINT = 22;
  public static final int CONST = 7;
  public static final int error = 1;
  public static final int NEW = 13;
  public static final int LSBRACE = 11;
  public static final int MUL = 19;
  public static final int VOID = 17;
  public static final int RSBRACE = 12;
}

