
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 10 12:50:18 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 10;
  public static final int CHAR = 15;
  public static final int SEMIC = 11;
  public static final int CONTINUE = 42;
  public static final int LPAREN = 28;
  public static final int LESS = 29;
  public static final int MINUS = 24;
  public static final int RPAREN = 7;
  public static final int AND = 27;
  public static final int LESS_OR_EQUAL = 21;
  public static final int OR = 43;
  public static final int COMMA = 12;
  public static final int CLASS = 40;
  public static final int INC = 36;
  public static final int PERC = 25;
  public static final int DIV = 23;
  public static final int HIGHER_OR_EQUAL = 44;
  public static final int PLUS = 6;
  public static final int IF = 9;
  public static final int IS_EQUAL = 31;
  public static final int DOT = 22;
  public static final int IS_NOT_EQUAL = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RETURN = 41;
  public static final int LSBRACE = 16;
  public static final int EQUAL = 13;
  public static final int RSBRACE = 17;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int HIGHER = 35;
  public static final int NUMBER = 14;
  public static final int BREAK = 32;
  public static final int IDENT = 3;
  public static final int VOID = 26;
  public static final int LBRACE = 4;
  public static final int ELSE = 8;
  public static final int READ = 34;
  public static final int WHILE = 37;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 19;
  public static final int PROG = 2;
  public static final int DEC = 45;
  public static final int DO = 39;
  public static final int PRINT = 38;
}

